// Script to add mnemonic memory tricks to words
// These connect the Dutch sound to the English meaning

const fs = require('fs');
const path = require('path');

const wordsPath = path.join(__dirname, '../src/data/words.json');
const words = JSON.parse(fs.readFileSync(wordsPath, 'utf8'));

// Hand-crafted mnemonics that connect Dutch sound to English meaning
const mnemonics = {
  // Common verbs
  'krijgen': 'CRY when you don\'t GET what you want',
  'eten': 'ATE-en, you ATE your food',
  'drinken': 'DRINK-en sounds like DRINK',
  'gaan': 'GONE - I\'m GONE, I GO',
  'komen': 'COME-en sounds like COME',
  'hebben': 'HAVE-ben, I HAVE it',
  'zijn': 'ZINE - to BE in a magazine/zine',
  'willen': 'WILL-en, I WILL do what I WANT',
  'kunnen': 'CAN-nen, I CAN do it',
  'moeten': 'MOOT-en point - you MUST decide',
  'mogen': 'MAY-gen, you MAY go',
  'zien': 'SEEN - I have SEEN it',
  'horen': 'HEAR-en sounds like HEAR',
  'weten': 'WIT-en, use your WIT to KNOW',
  'kennen': 'KEN someone - to KNOW a person',
  'denken': 'THINK-en sounds like THINK',
  'zeggen': 'SAY-gen, SAY something',
  'vragen': 'FRA-gen - the FRA asks a question',
  'geven': 'GIVE-en sounds like GIVE',
  'nemen': 'NAME-en - TAKE down their NAME',
  'maken': 'MAKE-en sounds like MAKE',
  'werken': 'WORK-en sounds like WORK',
  'leren': 'LEARN-en sounds like LEARN',
  'schrijven': 'SCRIBE-ven - a SCRIBE WRITES',
  'lezen': 'LAYS-en - she LAYS down to READ',
  'spreken': 'SPEAK-en sounds like SPEAK',
  'begrijpen': 'Be-GRIP-en - GRIP the concept, UNDERSTAND',
  'vinden': 'FIND-en sounds like FIND',
  'zoeken': 'SEEK-en sounds like SEEK/SEARCH',
  'kopen': 'COPE-en - COPE with the cost when you BUY',
  'betalen': 'Pay-TAHL-en - PAY the bill',
  'wonen': 'WON a house to LIVE in',
  'slapen': 'SLAP-en yourself awake from SLEEP',
  'lopen': 'LOPE-en - LOPE means to WALK',
  'rijden': 'RIDE-en sounds like RIDE/DRIVE',
  'wachten': 'WATCH-en the clock while you WAIT',
  'blijven': 'Be-LIVE-en - STAY alive, STAY here',
  'vertrekken': 'TREK-ken away - LEAVE on a trek',
  'aankomen': 'On-COME-en - ARRIVE, come on!',
  'stoppen': 'STOP-pen sounds like STOP',
  'beginnen': 'BEGIN-nen sounds like BEGIN',
  'eindigen': 'END-igen sounds like END',
  'proberen': 'PROBE-eren - PROBE/TRY it out',
  'vergeten': 'For-GET-en - FORGET it',
  'onthouden': 'On-HOLD-en - HOLD onto the memory, REMEMBER',
  'bellen': 'BELL-en - ring the BELL to CALL',
  'sturen': 'STEER-en - STEER the message, SEND it',
  'houden': 'HOLD-en sounds like HOLD',
  'helpen': 'HELP-en sounds like HELP',
  'kijken': 'KIKE-en - LOOK with your eyes',
  'luisteren': 'LUST-eren to LISTEN with desire',
  'voelen': 'FEEL-en sounds like FEEL',
  'zitten': 'SIT-ten sounds like SIT',
  'staan': 'STAND - staan sounds like STAND',
  'liggen': 'LIE-gen down, LIE there',
  'vallen': 'FALL-en sounds like FALL',
  'leven': 'LIVE-en sounds like LIVE',
  'groeien': 'GROW-en sounds like GROW',
  'veranderen': 'VARY-anderen - things VARY when they CHANGE',
  'verliezen': 'ver-LOSE-en - you LOSE it',
  'winnen': 'WIN-nen sounds like WIN',
  'spelen': 'PLAY-en - sPELen sounds like PLAY',
  'zwemmen': 'SWIM-men sounds like SWIM',
  'fietsen': 'FEATS-en on a bike - cycling FEATS',
  'rennen': 'RUN-nen sounds like RUN',
  'dansen': 'DANCE-en sounds like DANCE',
  'zingen': 'SING-en sounds like SING',
  'koken': 'COOK-en sounds like COOK',
  'bakken': 'BAKE-en sounds like BAKE',
  'wassen': 'WASH-en sounds like WASH',
  'ontmoeten': 'On-MEET-en - MEET someone',
  'bezoeken': 'Be-SEEK-en - SEEK out, VISIT',
  'bestellen': 'Be-STELL-en - ORDER at a stall',
  'huren': 'HIRE-en sounds like RENT/HIRE',
  'verkopen': 'For-KOPEN - for sale, SELL',
  'verdienen': 'For-DINE-en - EARN money to dine',
  'dragen': 'DRAG-en - DRAG what you CARRY/WEAR',

  // Nouns
  'huis': 'HOUSE sounds like HUIS',
  'water': 'WATER is the same!',
  'dag': 'DAY - dag sounds like day',
  'week': 'WEEK is the same!',
  'maand': 'MONTH - maand sounds like MONTH',
  'jaar': 'YEAR - jaar sounds like YEAR',
  'tijd': 'TIDE of TIME - tijd',
  'uur': 'HOUR - uur sounds like OUR/HOUR',
  'minuut': 'MINUTE sounds like minuut',
  'man': 'MAN is the same!',
  'vrouw': 'FRAU/FROW - a WOMAN/WIFE',
  'kind': 'KIND to the CHILD',
  'vader': 'FATHER - vader like Darth Vader',
  'moeder': 'MOTHER - moeder sounds similar',
  'zoon': 'SON - zoon sounds like SON',
  'dochter': 'DAUGHTER - dochter sounds similar',
  'vriend': 'FRIEND - vriend sounds like FRIEND',
  'boek': 'BOOK - boek sounds like BOOK',
  'auto': 'AUTO/CAR is the same!',
  'fiets': 'FEATS on a BICYCLE',
  'trein': 'TRAIN - trein sounds like TRAIN',
  'school': 'SCHOOL is the same!',
  'werk': 'WORK - werk sounds like WORK',
  'geld': 'GOLD/GELD - MONEY',
  'stad': 'STADT - a CITY/state',
  'land': 'LAND/COUNTRY is the same!',
  'koffie': 'COFFEE - koffie sounds like COFFEE',
  'thee': 'TEA - thee sounds like TEA',
  'weg': 'WAY/ROAD - weg sounds like WAY',
  'straat': 'STREET - straat sounds like STREET',
  'deur': 'DOOR - deur sounds like DOOR',
  'hond': 'HOUND/DOG - hond sounds like HOUND',
  'kat': 'CAT - kat sounds like CAT',
  'zon': 'SUN - zon sounds like SUN',
  'maan': 'MOON - maan sounds like MOON',
  'ster': 'STAR - ster sounds like STAR',
  'boom': 'A tree goes BOOM when it falls',
  'bloem': 'BLOOM - a FLOWER blooms',
  'tuin': 'TUNE in the GARDEN',
  'kamer': 'CAMERA in the ROOM',
  'bed': 'BED is the same!',
  'stoel': 'STOOL/CHAIR - stoel sounds like STOOL',
  'tafel': 'TABLE - tafel sounds like TABLE',
  'raam': 'FRAME of a WINDOW',
  'muur': 'MURAL on the WALL',
  'vloer': 'FLOOR - vloer sounds like FLOOR',
  'dak': 'DECK/ROOF on top',
  'trap': 'TRAP door on STAIRS',
  'lichaam': 'LIE down your BODY',
  'hoofd': 'HOOD on your HEAD',
  'haar': 'HAIR - haar sounds like HAIR',
  'oog': 'OOH look with your EYE',
  'oor': 'EAR - oor sounds similar',
  'neus': 'NOSE - neus sounds similar',
  'mond': 'MOUTH - mond sounds like MOUTH',
  'tand': 'TOOTH/DENTAL - tand',
  'hand': 'HAND is the same!',
  'arm': 'ARM is the same!',
  'been': 'BONE in your LEG',
  'voet': 'FOOT - voet sounds like FOOT',
  'hart': 'HEART - hart sounds like HEART',
  'brood': 'BREAD - brood sounds like BREAD',
  'kaas': 'CHEESE - say KAAS for photos!',
  'melk': 'MILK - melk sounds like MILK',
  'ei': 'EGG - ei sounds like EGG (aye)',
  'vlees': 'FLESH/MEAT - vlees',
  'vis': 'FISH - vis sounds like FISH',
  'groente': 'GREEN-te VEGETABLES',
  'fruit': 'FRUIT is the same!',
  'appel': 'APPLE - appel sounds like APPLE',
  'sinaasappel': 'Sinas-APPLE - ORANGE',
  'banaan': 'BANANA - banaan sounds like BANANA',
  'aardappel': 'EARTH-APPLE - POTATO',
  'rijst': 'RICE - rijst sounds like RICE',
  'soep': 'SOUP - soep sounds like SOUP',
  'zout': 'SALT - zout sounds like SALT',
  'suiker': 'SUGAR - suiker sounds like SUGAR',
  'bier': 'BEER - bier sounds like BEER',
  'wijn': 'WINE - wijn sounds like WINE',
  'glas': 'GLASS - glas is the same!',
  'bord': 'BOARD/PLATE - bord',
  'mes': 'MESS with a KNIFE',
  'vork': 'FORK - vork sounds like FORK',
  'lepel': 'LADLE/SPOON - lepel',
  'kleren': 'CLOTHING - kleren',
  'jas': 'JACKET - jas sounds similar',
  'broek': 'BRITCHES/PANTS - broek',
  'rok': 'ROCK a SKIRT',
  'jurk': 'JERK in a DRESS',
  'schoen': 'SHOE - schoen sounds like SHOE',
  'tas': 'TOSS in a BAG',
  'horloge': 'HOUR-loge WATCH',
  'telefoon': 'TELEPHONE is the same!',
  'computer': 'COMPUTER is the same!',
  'internet': 'INTERNET is the same!',
  'probleem': 'PROBLEM - probleem sounds like PROBLEM',
  'vraag': 'FRAAG/QUESTION - I ask',
  'antwoord': 'ANSWER - antwoord',
  'naam': 'NAME - naam sounds like NAME',
  'nummer': 'NUMBER - nummer sounds like NUMBER',
  'prijs': 'PRICE - prijs sounds like PRICE',
  'euro': 'EURO is the same!',
  'cent': 'CENT is the same!',

  // Adjectives
  'groot': 'GREAT/BIG - groot',
  'klein': 'Clean and SMALL',
  'goed': 'GOOD - goed sounds like GOOD',
  'slecht': 'SLACKED off = BAD',
  'mooi': 'MOO-y BEAUTIFUL cow',
  'lekker': 'LICK-er - TASTY, lick it!',
  'warm': 'WARM is the same!',
  'koud': 'COLD - koud sounds like COLD',
  'nieuw': 'NEW - nieuw sounds like NEW',
  'oud': 'OLD - oud sounds like OLD',
  'jong': 'YOUNG - jong sounds like YOUNG',
  'lang': 'LONG/TALL - lang sounds like LONG',
  'kort': 'CUT SHORT - kort',
  'snel': 'SNELL/FAST - quick as a bell',
  'langzaam': 'LONG-zaam - takes LONG, SLOW',
  'blij': 'Be-LIE - I\'m HAPPY, no lie!',
  'verdrietig': 'For-DRIP-tig - DRIP tears, SAD',
  'moe': 'MOE tired - so TIRED',
  'ziek': 'SICK - ziek sounds like SICK',
  'gezond': 'Good-SOUND = HEALTHY',
  'makkelijk': 'MAKE-elijk - EASY to make',
  'moeilijk': 'MOY-lijk - DIFFICULT to enjoy',
  'interessant': 'INTERESTING is the same!',
  'saai': 'SIGH - so BORING',
  'duur': 'DEAR/EXPENSIVE - costs dear',
  'goedkoop': 'GOOD-koop - GOOD deal, CHEAP',
  'gratis': 'GRATIS/FREE is the same!',
  'vol': 'VOLUME is FULL',
  'leeg': 'LEAGUE of nothing - EMPTY',
  'open': 'OPEN is the same!',
  'dicht': 'TIGHT/CLOSED - dicht',
  'licht': 'LIGHT - licht sounds like LIGHT',
  'donker': 'DUNKER in the DARK',
  'droog': 'DROUGHT = DRY',
  'nat': 'NOT dry = WET',
  'schoon': 'SHINE = CLEAN',
  'vies': 'VICE is DIRTY',
  'sterk': 'STARK/STRONG',
  'zwak': 'WHACK = WEAK',
  'rijk': 'RICH - rijk sounds like RICH',
  'arm': 'POOR - same as arm (limb)',
  'druk': 'RUCK/BUSY - in a ruck',
  'stil': 'STILL/QUIET - stil',
  'luid': 'LOUD - luid sounds like LOUD',
  'vroeg': 'FROG wakes EARLY',
  'laat': 'LATE - laat sounds like LATE',
  'echt': 'ACTUAL/REAL - echt',
  'vals': 'FALSE - vals sounds like FALSE',
  'zeker': 'SECURE/CERTAIN - zeker',
  'mogelijk': 'MOGE-lijk - POSSIBLE maybe',
  'nodig': 'NEED-ig - NECESSARY/needed',
  'belangrijk': 'Be-LONG-rijk - IMPORTANT to belong',
  'geweldig': 'Ge-WELD-ig - WELDED great, WONDERFUL',
  'verschrikkelijk': 'For-SHRIEK-elijk - SHRIEK, TERRIBLE',
  'vreemd': 'FREMD/STRANGE - foreign',
  'bekend': 'Be-KENNED - KNOWN/FAMOUS',
  'anders': 'OTHER/DIFFERENT - anders',
  'hetzelfde': 'Het-SELF-de - SAME self',

  // Adverbs & others
  'wat': 'WHAT - wat sounds like WHAT',
  'wie': 'WE/WHO - who are we',
  'waar': 'WHERE - waar sounds like WHERE',
  'wanneer': 'WHEN-eer sounds like WHEN',
  'waarom': 'WHERE-om - WHY/wherefore',
  'hoe': 'HOW - hoe sounds like HOW',
  'hoeveel': 'HOW-veel - HOW MUCH/MANY',
  'omdat': 'Om-THAT - BECAUSE of that',
  'maar': 'MAR/BUT - but mars it',
  'en': 'AND - en sounds like AND',
  'of': 'OR/OF - of sounds like OR',
  'als': 'ALLS - IF all goes well',
  'dan': 'THAN/THEN - dan',
  'nu': 'NOW - nu sounds like NOW',
  'altijd': 'ALL-tijd - ALL TIME, ALWAYS',
  'nooit': 'NO-it - NEVER, no way',
  'soms': 'SOME-times',
  'vaak': 'FOCK/OFTEN - very often',
  'hier': 'HERE - hier sounds like HERE',
  'daar': 'THERE - daar sounds like THERE',
  'links': 'LINKS to the LEFT',
  'rechts': 'RECTS/RIGHT direction',
  'boven': 'ABOVE - boven sounds similar',
  'onder': 'UNDER - onder sounds like UNDER',
  'voor': 'FORE/BEFORE - voor',
  'achter': 'AFTER/BEHIND - achter',
  'naast': 'NEXT to - naast',
  'tussen': 'TWIXT/BETWEEN - tussen',
  'binnen': 'BIN/INSIDE - binnen',
  'buiten': 'BOUT/OUTSIDE - buiten',
  'ver': 'FAR - ver sounds like FAR',
  'dichtbij': 'DICHT-by - CLOSE BY',
  'samen': 'SAME-n - TOGETHER, same group',
  'alleen': 'ALL-een - ALL ONE, ALONE',
  'bijna': 'BYE-na - ALMOST bye',
  'heel': 'WHOLE/VERY - heel',
  'erg': 'ERG of energy - VERY',
  'te': 'TOO - te sounds like TOO',
  'zo': 'SO - zo sounds like SO',
  'ja': 'YA/YES - ja',
  'nee': 'NAY/NO - nee',
  'misschien': 'MISS-schien - MAYBE miss it',
  'natuurlijk': 'NATURAL-lijk - NATURALLY/OF COURSE',
  'alsjeblieft': 'ALS-je-BELIEVE - PLEASE believe',
  'dank': 'THANK - dank sounds like THANK',
  'sorry': 'SORRY is the same!',
  'welkom': 'WELCOME - welkom sounds like WELCOME',

  // Numbers
  'een': 'ONE - een sounds like ONE',
  'twee': 'TWO - twee sounds like TWO',
  'drie': 'THREE - drie sounds like THREE',
  'vier': 'FOUR - vier sounds like FOUR',
  'vijf': 'FIVE - vijf sounds like FIVE',
  'zes': 'SIX - zes sounds similar',
  'zeven': 'SEVEN - zeven sounds like SEVEN',
  'acht': 'EIGHT - acht sounds like EIGHT',
  'negen': 'NINE - negen sounds like NINE',
  'tien': 'TEN - tien sounds like TEN',
  'elf': 'ELEVEN - elf sounds like ELEVEN',
  'twaalf': 'TWELVE - twaalf sounds like TWELVE',
  'dertien': 'THIRTEEN - dertien',
  'veertien': 'FOURTEEN - veertien',
  'vijftien': 'FIFTEEN - vijftien',
  'twintig': 'TWENTY - twintig sounds like TWENTY',
  'dertig': 'THIRTY - dertig',
  'veertig': 'FORTY - veertig',
  'vijftig': 'FIFTY - vijftig',
  'honderd': 'HUNDRED - honderd sounds like HUNDRED',
  'duizend': 'THOUSAND - duizend',
  'miljoen': 'MILLION - miljoen sounds like MILLION',

  // Days & months
  'maandag': 'MOON-dag - MONDAY',
  'dinsdag': 'DINS-dag - TUESDAY (Tiw\'s day)',
  'woensdag': 'WODEN\'s-dag - WEDNESDAY',
  'donderdag': 'THUNDER-dag - THURSDAY (Thor)',
  'vrijdag': 'FRI-dag - FRIDAY (Freya)',
  'zaterdag': 'SATURN-dag - SATURDAY',
  'zondag': 'SUN-dag - SUNDAY',
  'januari': 'JANUARY - januari',
  'februari': 'FEBRUARY - februari',
  'maart': 'MARCH - maart',
  'april': 'APRIL - april',
  'mei': 'MAY - mei',
  'juni': 'JUNE - juni',
  'juli': 'JULY - juli',
  'augustus': 'AUGUST - augustus',
  'september': 'SEPTEMBER - september',
  'oktober': 'OCTOBER - oktober',
  'november': 'NOVEMBER - november',
  'december': 'DECEMBER - december',

  // More verbs
  'doen': 'DO-en sounds like DO',
  'laten': 'LET-en - LET it be',
  'pakken': 'PACK-en - PACK/GRAB it',
  'zetten': 'SET-ten - SET it down',
  'leggen': 'LAY-gen - LAY it down',
  'hangen': 'HANG-en sounds like HANG',
  'trekken': 'TREK-ken - PULL/TREK',
  'duwen': 'DO-wen - DO push = PUSH',
  'draaien': 'TURN - draai like a dial',
  'breken': 'BREAK-en sounds like BREAK',
  'snijden': 'SNIDE cut - CUT snidely',
  'kiezen': 'CHOOSE - kiezen',
  'bouwen': 'BUILD - bouwen',
  'tekenen': 'TOKEN/DRAW - tekenen',
  'schilderen': 'SHIELD-eren - PAINT a shield',
  'vliegen': 'FLY-gen sounds like FLY',
  'zweven': 'SWEVE/FLOAT - zweven',
  'klimmen': 'CLIMB-men sounds like CLIMB',
  'springen': 'SPRING-en sounds like JUMP/SPRING',
  'gooien': 'GO-yen - GO THROW it',
  'vangen': 'FANG-en - CATCH with fangs',
  'raken': 'RACK-en - HIT the rack',
  'missen': 'MISS-en sounds like MISS',
  'halen': 'HAUL-en - FETCH/HAUL it',
  'brengen': 'BRING-en sounds like BRING',
  'kloppen': 'KLOP-pen - KNOCK klop klop',
  'openen': 'OPEN-en sounds like OPEN',
  'sluiten': 'SHUT-en - CLOSE/SHUT',
  'drukken': 'PUSH/PRESS - druk button',
  'indrukken': 'IMPRESS - in-drukken',
  'aanraken': 'On-RAKE-en - TOUCH gently',
  'vasthouden': 'FAST-HOLD-en - HOLD FAST',
  'loslaten': 'LOOSE-LET-en - LET GO loose',
  'verzamelen': 'For-SAMPLE-en - COLLECT samples',
  'gebruiken': 'Ge-BROOK-en - USE the brook',
  'produceren': 'PRODUCE-eren - PRODUCE',
  'creëren': 'CREATE-eren - CREATE',
  'vernietigen': 'For-NEGATE-igen - DESTROY/negate',
  'redden': 'RESCUE/SAVE - red alert!',
  'beschermen': 'Be-SHERM-en - SHIELD/PROTECT',
  'aanvallen': 'On-FALL-en - ATTACK/fall upon',
  'verdedigen': 'For-DEFEND-igen - DEFEND',
  'ontsnappen': 'On-SNAP-pen - SNAP away, ESCAPE',
  'verbergen': 'For-BURY-gen - BURY/HIDE',
  'zoeken': 'SEEK-en - SEEK/SEARCH',
  'ontdekken': 'On-DECK-en - DISCOVER on deck',
  'herinneren': 'Her-INNER-en - REMEMBER inner thoughts',
  'dromen': 'DREAM-en sounds like DREAM',
  'wensen': 'WISH-en - WISH/wensen',
  'hopen': 'HOPE-en sounds like HOPE',
  'vrezen': 'FREEZE-en with FEAR',
  'haten': 'HATE-en sounds like HATE',
  'liefhebben': 'LIFE-HAVE-en - LOVE life',
  'trouwen': 'TRUE-wen - MARRY truly',
  'scheiden': 'SHED-en - SHED/DIVORCE',
  'geboren': 'Ge-BORN-en - BORN',
  'sterven': 'STARVE/DIE - sterven',
  'ademen': 'ADAM-en - BREATHE like Adam',
  'hoesten': 'COUGH - hoesten sounds similar',
  'niezen': 'SNEEZE - niezen',
  'huilen': 'HOWL-en - CRY/howl',
  'lachen': 'LAUGH-en sounds like LAUGH',
  'glimlachen': 'GLEAM-LAUGH-en - SMILE gleaming',
  'schreeuwen': 'SCREAM/SHOUT - schreeuwen',
  'fluisteren': 'FLUSTER-en - WHISPER flustered',
  'praten': 'PRATE-en - TALK/prate on',
  'discussiëren': 'DISCUSS-ieren - DISCUSS',
  'ruziën': 'RUSE-yen - ARGUE with ruse',
  'klagen': 'CLAIM-en - COMPLAIN/claim',
  'bedanken': 'Be-THANK-en - THANK someone',
  'feliciteren': 'FELICIT-eren - CONGRATULATE',
  'uitnodigen': 'OUT-NOOD-igen - INVITE out',
  'weigeren': 'WAGER-en - REFUSE the wager',
  'accepteren': 'ACCEPT-eren - ACCEPT',
  'toestaan': 'TO-STAND - ALLOW to stand',
  'verbieden': 'For-BID-en - FORBID',
  'dwingen': 'DING-en - FORCE the ding',
  'overtuigen': 'Over-TWIG-en - CONVINCE/twig it',
  'verrassen': 'For-RASS-en - SURPRISE',
  'schrikken': 'SHRIEK-en - SCARE/shriek',
  'ontspannen': 'On-SPAN-en - RELAX the span',
  'concentreren': 'CONCENTRATE-eren - CONCENTRATE',
  'studeren': 'STUDY-eren - STUDY',
  'oefenen': 'OEFEN-en - PRACTICE',
  'trainen': 'TRAIN-en - TRAIN',
  'presteren': 'PRESTER-en - PERFORM',
  'slagen': 'SLAY-gen - SLAY the test, PASS',
  'falen': 'FAIL-en sounds like FAIL',
  'plannen': 'PLAN-nen sounds like PLAN',
  'organiseren': 'ORGANIZE-eren - ORGANIZE',
  'beslissen': 'Be-SLIS-sen - make a DECISION',
  'adviseren': 'ADVISE-eren - ADVISE',
  'voorstellen': 'FORE-STELL-en - PROPOSE/SUGGEST',
  'aanbieden': 'On-BID-en - OFFER a bid',
  'beloven': 'Be-LOVE-en - PROMISE with love',
  'liegen': 'LIE-gen sounds like LIE',
  'bedriegen': 'Be-DRIEG-en - DECEIVE/betray',
  'vertrouwen': 'For-TRUE-wen - TRUST truly',
  'twijfelen': 'TWIVEL-en - DOUBT/waver',
  'beweren': 'Be-WARE-en - CLAIM/beware',
  'bewijzen': 'Be-WISE-en - PROVE wisely',
  'verklaren': 'For-CLEAR-en - EXPLAIN clearly',
  'beschrijven': 'Be-SCRIBE-en - DESCRIBE/scribe',
  'vertalen': 'For-TALE-en - TRANSLATE the tale',
  'uitleggen': 'OUT-LAY-gen - LAY OUT/EXPLAIN',
  'melden': 'MELD-en - MELD/REPORT',
  'aankondigen': 'On-KUND-igen - ANNOUNCE',
  'publiceren': 'PUBLISH-eren - PUBLISH',
  'delen': 'DEAL-en - DEAL/SHARE',
  'combineren': 'COMBINE-eren - COMBINE',
  'scheiden': 'SHADE-en - SEPARATE/shade',
  'mengen': 'MINGLE-en - MIX/mingle',
  'sorteren': 'SORT-eren - SORT',
  'rangschikken': 'RANK-schikken - ARRANGE ranks',
  'stapelen': 'STAPLE-en - STACK/staple',
  'vouwen': 'FOLD - vouwen sounds like FOLD',
  'rollen': 'ROLL-en sounds like ROLL',
  'schuiven': 'SHOVE-en - SLIDE/shove',
  'tillen': 'TILT-en - LIFT/tilt',
  'dragen': 'DRAG-en - CARRY/drag',
  'slepen': 'SCHLEP-en - DRAG/schlep',
  'glijden': 'GLIDE-en sounds like GLIDE',
  'struikelen': 'STRIKE-elen - STUMBLE/strike ground',
  'botsen': 'BOTS-en - BOT collision, COLLIDE',
  'crashen': 'CRASH-en - CRASH',
  'repareren': 'REPAIR-eren - REPAIR',
  'installeren': 'INSTALL-eren - INSTALL',
  'updaten': 'UPDATE-en - UPDATE',
  'downloaden': 'DOWNLOAD-en - DOWNLOAD',
  'uploaden': 'UPLOAD-en - UPLOAD',
  'printen': 'PRINT-en - PRINT',
  'kopiëren': 'COPY-eren - COPY',
  'plakken': 'PLAK-ken - PASTE/plaque',
  'verwijderen': 'For-WIDER-en - DELETE/widen gap',
  'opslaan': 'Op-SLAAN - SAVE/store',
  'laden': 'LOAD-en sounds like LOAD',

  // More nouns
  'wereld': 'WORLD - wereld sounds like WORLD',
  'natuur': 'NATURE - natuur sounds like NATURE',
  'lucht': 'LUFT/AIR - lucht',
  'weer': 'WEATHER - weer',
  'regen': 'RAIN - regen sounds like RAIN',
  'sneeuw': 'SNOW - sneeuw sounds like SNOW',
  'wind': 'WIND is the same!',
  'wolk': 'WALK through CLOUDS',
  'hemel': 'HIMMEL/SKY - hemel',
  'aarde': 'EARTH - aarde sounds like EARTH',
  'zee': 'SEA - zee sounds like SEA',
  'meer': 'MERE/LAKE - meer',
  'rivier': 'RIVER - rivier sounds like RIVER',
  'berg': 'BERG/MOUNTAIN - berg',
  'bos': 'BOSS of the FOREST',
  'veld': 'FIELD - veld sounds like FIELD',
  'eiland': 'EYE-LAND - ISLAND',
  'strand': 'STRAND of BEACH',
  'haven': 'HAVEN/PORT - haven',
  'brug': 'BRIDGE - brug',
  'gebouw': 'Ge-BUILD - BUILDING',
  'kantoor': 'CANTOR/OFFICE - kantoor',
  'fabriek': 'FABRIC-k - FACTORY',
  'winkel': 'WINK-el - SHOP wink',
  'restaurant': 'RESTAURANT is the same!',
  'café': 'CAFÉ is the same!',
  'hotel': 'HOTEL is the same!',
  'ziekenhuis': 'SICK-en-HOUSE - HOSPITAL',
  'apotheek': 'APOTHECARY - apotheek',
  'politie': 'POLICE - politie',
  'brandweer': 'BRAND-WEAR - FIRE BRIGADE',
  'ambulance': 'AMBULANCE is the same!',
  'kerk': 'KIRK/CHURCH - kerk',
  'museum': 'MUSEUM is the same!',
  'bioscoop': 'BIO-SCOPE - CINEMA',
  'theater': 'THEATER - theater',
  'park': 'PARK is the same!',
  'speeltuin': 'PLAY-TUNE - PLAYGROUND',
  'zwembad': 'SWIM-BAD - SWIMMING POOL',
  'bibliotheek': 'BIBLIO-theek - LIBRARY',
  'universiteit': 'UNIVERSITY - universiteit',
  'les': 'LESSON - les',
  'cursus': 'COURSE - cursus',
  'examen': 'EXAM - examen',
  'diploma': 'DIPLOMA is the same!',
  'baan': 'On the right track - JOB/career path',
  'salaris': 'SALARY - salaris',
  'baas': 'BOSS - baas sounds like BOSS',
  'collega': 'COLLEAGUE - collega',
  'klant': 'CLIENT - klant',
  'bedrijf': 'Be-DRIVE - COMPANY drives business',
  'markt': 'MARKET - markt sounds like MARKET',
  'economie': 'ECONOMY - economie',
  'regering': 'REIGNING - GOVERNMENT',
  'wet': 'What the law WETS - LAW',
  'recht': 'RIGHT/LAW - recht',
  'vrijheid': 'FREE-heid - FREEDOM',
  'vrede': 'FREED from war - PEACE',
  'oorlog': 'OAR-log - WAR log',
  'leger': 'LEGION/ARMY - leger',
  'wapen': 'WEAPON - wapen sounds like WEAPON',
  'gevaar': 'Ge-FAR - DANGER afar',
  'veiligheid': 'FAIL-ig-heid - no FAIL = SAFETY',
  'kunst': 'Can\'t miss ART - kunst',
  'muziek': 'MUSIC - muziek sounds like MUSIC',
  'film': 'FILM is the same!',
  'foto': 'PHOTO - foto sounds like PHOTO',
  'schilderij': 'SHIELD-erij - PAINTING on shield',
  'beeld': 'BEELD/IMAGE - beeld',
  'tekst': 'TEXT - tekst sounds like TEXT',
  'verhaal': 'For-HALL - STORY in the hall',
  'gedicht': 'Ge-DICHT - POEM tightly written',
  'lied': 'LEAD a SONG',
  'instrument': 'INSTRUMENT is the same!',
  'sport': 'SPORT is the same!',
  'wedstrijd': 'WED-strijd - MATCH/wedding of teams',
  'team': 'TEAM is the same!',
  'speler': 'PLAY-er - PLAYER',
  'winnaar': 'WIN-naar - WINNER',
  'verliezer': 'ver-LOSE-er - LOSER',
  'punt': 'POINT - punt',
  'doel': 'DUAL GOAL - doel',
  'bal': 'BALL - bal sounds like BALL',
  'spel': 'SPELL a GAME',
  'reis': 'RISE and TRAVEL',
  'vakantie': 'VACANT-ie - VACATION',
  'ticket': 'TICKET is the same!',
  'paspoort': 'PASSPORT - paspoort',
  'koffer': 'COFFER/SUITCASE - koffer',
  'vlucht': 'FLIGHT - vlucht',
  'station': 'STATION is the same!',
  'halte': 'HALT-e - STOP',
  'richting': 'RIGHT-ing - DIRECTION',
  'afstand': 'AF-STAND - DISTANCE stands',
  'snelheid': 'SNEL-heid - SPEED',
  'verkeer': 'For-CARE - TRAFFIC care',
  'auto': 'AUTO/CAR - auto',
  'bus': 'BUS is the same!',
  'metro': 'METRO is the same!',
  'tram': 'TRAM is the same!',
  'vliegtuig': 'FLY-THING - AIRPLANE',
  'boot': 'BOAT - boot sounds like BOAT',
  'schip': 'SHIP - schip sounds like SHIP',
  'motor': 'MOTOR is the same!',
  'benzine': 'BENZINE/GASOLINE - benzine',
  'garage': 'GARAGE is the same!',
  'straat': 'STREET - straat sounds like STREET',
  'hoek': 'HOOK/CORNER - hoek',
  'plein': 'PLAIN/SQUARE - plein',
  'centrum': 'CENTER - centrum',
  'wijk': 'WICK of NEIGHBORHOOD',
  'adres': 'ADDRESS - adres',
  'postcode': 'POSTCODE is the same!',
  'brief': 'BRIEF LETTER - brief',
  'envelop': 'ENVELOPE - envelop',
  'pakket': 'PACKET - pakket',
  'postkantoor': 'POST-CANTOR - POST OFFICE',
  'bank': 'BANK is the same!',
  'rekening': 'RECKONING - ACCOUNT/BILL',
  'lening': 'LEAN-ing - LOAN',
  'verzekering': 'For-SECURE-ing - INSURANCE',
  'contract': 'CONTRACT is the same!',
  'document': 'DOCUMENT is the same!',
  'formulier': 'FORM-ulier - FORM',
  'handtekening': 'HAND-TAKEN-ing - SIGNATURE',
  'vergadering': 'For-GATHER-ing - MEETING',
  'project': 'PROJECT is the same!',
  'idee': 'IDEA - idee sounds like IDEA',
  'plan': 'PLAN is the same!',
  'resultaat': 'RESULT-aat - RESULT',
  'succes': 'SUCCESS - succes',
  'mislukking': 'MISS-luck-ing - FAILURE',
  'ervaring': 'Ex-FARING - EXPERIENCE',
  'kennis': 'KEN-nis - KNOWLEDGE/to ken',
  'informatie': 'INFORMATION - informatie',
  'nieuws': 'NEWS - nieuws sounds like NEWS',
  'bericht': 'Be-REPORT - MESSAGE/REPORT',
  'email': 'EMAIL is the same!',
  'website': 'WEBSITE is the same!',
  'app': 'APP is the same!',
  'wachtwoord': 'WATCH-WORD - PASSWORD',
  'systeem': 'SYSTEM - systeem',
  'programma': 'PROGRAM - programma',
  'bestand': 'Be-STAND - FILE stands',
  'map': 'MAP/FOLDER - map',
  'scherm': 'SCREEN - scherm',
  'toetsenbord': 'TOUCH-en-BOARD - KEYBOARD',
  'muis': 'MOUSE - muis sounds like MOUSE',
  'printer': 'PRINTER is the same!',
  'camera': 'CAMERA is the same!',
  'batterij': 'BATTERY - batterij',
  'stroom': 'STREAM of ELECTRICITY',
  'lamp': 'LAMP is the same!',
  'machine': 'MACHINE is the same!',
  'apparaat': 'APPARATUS - DEVICE',
  'gereedschap': 'Ge-READY-schap - TOOLS ready',
  'materiaal': 'MATERIAL - materiaal',
  'stof': 'STUFF/FABRIC - stof',
  'plastic': 'PLASTIC is the same!',
  'glas': 'GLASS - glas',
  'metaal': 'METAL - metaal',
  'hout': 'HOUT sounds like WOOD (from Germanic)',
  'steen': 'STONE - steen sounds like STONE',
  'papier': 'PAPER - papier',
  'karton': 'CARTON - karton',

  // Remaining common words
  'iets': 'IT\'S SOMETHING - iets',
  'niets': 'NYET/NOTHING - niets',
  'iemand': 'I-MAND - SOMEONE I demand',
  'niemand': 'NO-MAND - NOBODY demanded',
  'alles': 'ALL-es - EVERYTHING',
  'veel': 'FEEL how MUCH/MANY',
  'weinig': 'WANE-ig - FEW, waning',
  'meer': 'MORE - meer sounds like MORE',
  'minder': 'MIND-er - LESS to mind',
  'genoeg': 'Ge-NOUGH - ENOUGH',
  'ongeveer': 'On-ge-FAIR - APPROXIMATELY fair',
  'precies': 'PRECISE-ies - EXACTLY',
  'helemaal': 'HELL-e-MAAL - COMPLETELY',
  'eindelijk': 'END-elijk - FINALLY at end',
  'plotseling': 'PLOT-seling - SUDDENLY in plot',
  'langzaam': 'LONG-zaam - SLOWLY, long time',
  'snel': 'Like a SNAIL? No, FAST!',
  'gisteren': 'YESTER-en - YESTERDAY',
  'vandaag': 'VAN-dag - of this DAY, TODAY',
  'morgen': 'MORNING - TOMORROW morning',
  'overmorgen': 'OVER-MORNING - DAY AFTER TOMORROW',
  'eergisteren': 'ERE-GISTEREN - DAY BEFORE YESTERDAY',
  'ochtend': 'OCH-TEND - MORNING tends',
  'middag': 'MID-DAG - AFTERNOON, mid-day',
  'avond': 'ADVENT - EVENING advent',
  'nacht': 'NIGHT - nacht sounds like NIGHT',
  'weekend': 'WEEKEND is the same!',
  'verjaardag': 'For-YEAR-dag - BIRTHDAY yearly',
  'feest': 'FEAST/PARTY - feest',
  'cadeau': 'CADEAU/GIFT - present',
  'verrassing': 'For-RASS-ing - SURPRISE',
};

// Add mnemonics to words
let added = 0;
for (const word of words) {
  const mnemonic = mnemonics[word.dutch];
  if (mnemonic && !word.mnemonic) {
    word.mnemonic = mnemonic;
    added++;
  }
}

// Write back
fs.writeFileSync(wordsPath, JSON.stringify(words, null, 2));
console.log(`Added ${added} mnemonics to words`);
