// Script to add more mnemonics for remaining words

const fs = require('fs');
const path = require('path');

const wordsPath = path.join(__dirname, '../src/data/words.json');
const words = JSON.parse(fs.readFileSync(wordsPath, 'utf8'));

// More mnemonics for words that don't have them yet
const moreMnemonics = {
  'plicht': 'PLIGHT of DUTY - your plight is your duty',
  'reden': 'REASON - reden sounds like REASON',
  'bericht': 'Be-REPORT - MESSAGE/report',
  'weer': 'WEATHER - weer sounds like WEATHER',
  'gevoel': 'Ge-FEEL - FEELING',
  'gedachte': 'Ge-THOUGHT - a THOUGHT',
  'voorbeeld': 'FORE-BEELD - EXAMPLE before you',
  'verschil': 'For-SKILL - DIFFERENCE in skill',
  'richting': 'RIGHT-ing - DIRECTION',
  'oplossing': 'Op-LOSS-ing - SOLUTION to loss',
  'mogelijkheid': 'MOGE-lijk-heid - POSSIBILITY maybe',
  'verantwoordelijkheid': 'For-ANSWER-lijk-heid - RESPONSIBILITY to answer',
  'ontwikkeling': 'Ont-WICK-eling - DEVELOPMENT unwicking',
  'betekenis': 'Be-TOKEN-is - MEANING/token',
  'waarde': 'WORTH - waarde sounds like WORTH',
  'kracht': 'CRAFT/POWER - kracht',
  'aandacht': 'On-DACHT - ATTENTION on thought',
  'invloed': 'IN-FLOOD - INFLUENCE floods in',
  'belang': 'Be-LONG - INTEREST/importance belongs',
  'doel': 'DUAL goal - GOAL/PURPOSE',
  'voordeel': 'FORE-DEAL - ADVANTAGE in the deal',
  'nadeel': 'NA-DEAL - DISADVANTAGE after deal',
  'effect': 'EFFECT is the same!',
  'resultaat': 'RESULT-aat - RESULT',
  'oorzaak': 'OOR-ZAAK - EAR the CAUSE',
  'gevolg': 'Ge-FOLLOW - CONSEQUENCE follows',
  'eis': 'ICE cold DEMAND',
  'behoefte': 'Be-HOOF-te - NEED hooves',
  'kans': 'CHANCE - kans sounds like CHANCE',
  'risico': 'RISK-o - RISK',
  'voorstel': 'FORE-STELL - PROPOSAL put forth',
  'besluit': 'Be-SLUIT - DECISION to shut',
  'regel': 'RULE - regel sounds like RULE',
  'wet': 'WET the LAW',
  'systeem': 'SYSTEM - systeem',
  'methode': 'METHOD - methode',
  'proces': 'PROCESS - proces',
  'structuur': 'STRUCTURE - structuur',
  'organisatie': 'ORGANIZATION - organisatie',
  'groep': 'GROUP - groep sounds like GROUP',
  'lid': 'LID/MEMBER - lid of group',
  'leider': 'LEADER - leider sounds like LEADER',
  'rol': 'ROLE - rol sounds like ROLE',
  'taak': 'TASK - taak sounds like TASK',
  'functie': 'FUNCTION - functie',
  'positie': 'POSITION - positie',
  'niveau': 'NIVEAU/LEVEL - niveau',
  'gebied': 'Ge-BID - AREA/field bid on',
  'sector': 'SECTOR - sector',
  'industrie': 'INDUSTRY - industrie',
  'markt': 'MARKET - markt',
  'klant': 'CLIENT - klant',
  'dienst': 'SERVICE - dienst',
  'product': 'PRODUCT - product',
  'kwaliteit': 'QUALITY - kwaliteit',
  'prijs': 'PRICE - prijs',
  'kosten': 'COST-en - COSTS',
  'winst': 'WIN-st - PROFIT from winning',
  'verlies': 'For-LOSE - LOSS',
  'schuld': 'Should pay DEBT - schuld',
  'bezit': 'Be-SIT on PROPERTY',
  'eigendom': 'EIGEN-dom - OWN PROPERTY',
  'huur': 'HIRE/RENT - huur',
  'aankoop': 'On-KOOP - PURCHASE',
  'verkoop': 'For-KOOP - SALE',
  'handel': 'HANDLE TRADE - handel',
  'afspraak': 'AF-SPRAAK - APPOINTMENT to speak',
  'vergadering': 'For-GATHER-ing - MEETING',
  'gesprek': 'Ge-SPEAK - CONVERSATION',
  'discussie': 'DISCUSSION - discussie',
  'onderwerp': 'UNDER-WERP - SUBJECT/TOPIC underneath',
  'punt': 'POINT - punt',
  'vraagstuk': 'VRAAG-stuck - QUESTION stuck on',
  'antwoord': 'ANSWER-word - ANSWER',
  'oplossing': 'Op-LOSS-ing - SOLUTION to loss',
  'idee': 'IDEA - idee',
  'mening': 'MEAN-ing - OPINION/meaning',
  'standpunt': 'STAND-POINT - viewpoint',
  'argument': 'ARGUMENT - argument',
  'bewijs': 'Be-WISE - PROOF/evidence wisely',
  'conclusie': 'CONCLUSION - conclusie',
  'theorie': 'THEORY - theorie',
  'praktijk': 'PRACTICE - praktijk',
  'ervaring': 'Ex-FARING - EXPERIENCE faring',
  'kennis': 'KEN-nis - KNOWLEDGE to ken',
  'vaardigheid': 'FARING-heid - SKILL in faring',
  'talent': 'TALENT - talent',
  'eigenschap': 'EIGEN-schap - CHARACTERISTIC/own-ship',
  'persoonlijkheid': 'PERSONAL-lijk-heid - PERSONALITY',
  'karakter': 'CHARACTER - karakter',
  'gedrag': 'Ge-DRAG - BEHAVIOR dragged out',
  'houding': 'HOLDING - ATTITUDE held',
  'reactie': 'REACTION - reactie',
  'emotie': 'EMOTION - emotie',
  'angst': 'ANGST/FEAR - angst',
  'woede': 'WODE/ANGER - woede',
  'vreugde': 'FRAUD-less JOY - vreugde',
  'verdriet': 'For-DRIP - SORROW dripping tears',
  'liefde': 'LIFE-de - LOVE of life',
  'haat': 'HATE - haat sounds like HATE',
  'respect': 'RESPECT - respect',
  'vertrouwen': 'For-TRUE-wen - TRUST truly',
  'twijfel': 'TWIVEL - DOUBT/waver',
  'hoop': 'HOPE - hoop sounds like HOPE',
  'wens': 'WISH - wens',
  'droom': 'DREAM - droom sounds like DREAM',
  'werkelijkheid': 'WORK-elijk-heid - REALITY of work',
  'waarheid': 'WHERE-heid - TRUTH is where',
  'leugen': 'LAY-gen - LIE laid down',
  'geheim': 'Ge-HIDE - SECRET hidden',
  'feit': 'FACT - feit sounds like FATE/FACT',
  'detail': 'DETAIL - detail',
  'aspect': 'ASPECT - aspect',
  'factor': 'FACTOR - factor',
  'element': 'ELEMENT - element',
  'deel': 'DEAL/PART - deel',
  'geheel': 'Ge-WHOLE - WHOLE',
  'helft': 'HALF-t - HALF',
  'kwart': 'QUART-er - QUARTER',
  'procent': 'PERCENT - procent',
  'aantal': 'On-TALLY - NUMBER/count',
  'hoeveelheid': 'HOE-veel-heid - QUANTITY how much',
  'grootte': 'GROOT-te - SIZE/greatness',
  'lengte': 'LENGTH-e - LENGTH',
  'breedte': 'BREADTH-e - WIDTH',
  'hoogte': 'HEIGHT-e - HEIGHT',
  'diepte': 'DEEP-te - DEPTH',
  'afstand': 'AF-STAND - DISTANCE standing',
  'snelheid': 'SNEL-heid - SPEED',
  'tempo': 'TEMPO - tempo',
  'ritme': 'RHYTHM - ritme',
  'frequentie': 'FREQUENCY - frequentie',
  'periode': 'PERIOD - periode',
  'fase': 'PHASE - fase',
  'moment': 'MOMENT - moment',
  'ogenblik': 'EYE-blink - MOMENT/instant',
  'seconde': 'SECOND - seconde',
  'begin': 'BEGIN - begin',
  'einde': 'END-e - END',
  'midden': 'MIDDLE-n - MIDDLE',
  'grens': 'BORDER - grens',
  'rand': 'RIM/EDGE - rand',
  'kant': 'CANT/SIDE - kant',
  'hoek': 'HOOK/CORNER - hoek',
  'lijn': 'LINE - lijn sounds like LINE',
  'cirkel': 'CIRCLE - cirkel',
  'vorm': 'FORM - vorm sounds like FORM',
  'figuur': 'FIGURE - figuur',
  'beeld': 'BUILD an IMAGE - beeld',
  'kleur': 'COLOR - kleur sounds like COLOR',
  'rood': 'RED - rood sounds like RED',
  'blauw': 'BLUE - blauw sounds like BLUE',
  'groen': 'GREEN - groen sounds like GREEN',
  'geel': 'YELLOW - geel',
  'wit': 'WHITE - wit sounds like WHITE',
  'zwart': 'SCHWARTZ/BLACK - zwart',
  'grijs': 'GRAY - grijs sounds like GRAY',
  'bruin': 'BROWN - bruin sounds like BROWN',
  'oranje': 'ORANGE - oranje',
  'paars': 'PURPLE - paars',
  'roze': 'ROSE/PINK - roze',
  'licht': 'LIGHT - licht',
  'donker': 'DUNKER/DARK - donker',
  'helder': 'HELD bright - CLEAR/bright',
  'vaag': 'VAGUE - vaag',
  'scherp': 'SHARP - scherp',
  'zacht': 'SOFT - zacht sounds soft',
  'hard': 'HARD - hard',
  'glad': 'GLAD/SMOOTH - glad',
  'ruw': 'ROUGH - ruw',
  'nat': 'NOT dry - WET',
  'droog': 'DROUGHT/DRY - droog',
  'vochtig': 'FOCHT-ig - HUMID/moist',
  'stoffig': 'STUFF-ig - DUSTY with stuff',
  'schoon': 'SHEEN/CLEAN - schoon',
  'vuil': 'FOUL/DIRTY - vuil',
  'vers': 'FRESH - vers sounds like VERSE/FRESH',
  'oud': 'OLD - oud',
  'nieuw': 'NEW - nieuw',
  'modern': 'MODERN - modern',
  'traditioneel': 'TRADITIONAL - traditioneel',
  'normaal': 'NORMAL - normaal',
  'vreemd': 'FREMD/STRANGE - vreemd',
  'gewoon': 'Ge-WOON - ORDINARY/usual',
  'bijzonder': 'BY-SONDER - SPECIAL/particular',
  'speciaal': 'SPECIAL - speciaal',
  'uniek': 'UNIQUE - uniek',
  'algemeen': 'ALL-gemeen - GENERAL',
  'specifiek': 'SPECIFIC - specifiek',
  'lokaal': 'LOCAL - lokaal',
  'nationaal': 'NATIONAL - nationaal',
  'internationaal': 'INTERNATIONAL - internationaal',
  'wereldwijd': 'WORLD-WIDE - worldwide',
  'openbaar': 'OPEN-BAAR - PUBLIC/open',
  'privé': 'PRIVATE - privé',
  'officieel': 'OFFICIAL - officieel',
  'persoonlijk': 'PERSONAL-lijk - PERSONAL',
  'sociaal': 'SOCIAL - sociaal',
  'economisch': 'ECONOMIC - economisch',
  'politiek': 'POLITICAL - politiek',
  'cultureel': 'CULTURAL - cultureel',
  'historisch': 'HISTORICAL - historisch',
  'wetenschappelijk': 'WETEN-SCHAP-elijk - SCIENTIFIC knowledge',
  'technisch': 'TECHNICAL - technisch',
  'praktisch': 'PRACTICAL - praktisch',
  'theoretisch': 'THEORETICAL - theoretisch',
  'positief': 'POSITIVE - positief',
  'negatief': 'NEGATIVE - negatief',
  'neutraal': 'NEUTRAL - neutraal',
  'actief': 'ACTIVE - actief',
  'passief': 'PASSIVE - passief',
  'direct': 'DIRECT - direct',
  'indirect': 'INDIRECT - indirect',
  'logisch': 'LOGICAL - logisch',
  'redelijk': 'REASONABLE - redelijk',
  'eerlijk': 'HONOR-lijk - HONEST/fair',
  'oneerlijk': 'Un-HONOR-lijk - UNFAIR/dishonest',
  'rechtvaardig': 'RECHT-fair-dig - JUST/fair',
  'streng': 'STRINGENT/STRICT - streng',
  'mild': 'MILD - mild',
  'flexibel': 'FLEXIBLE - flexibel',
  'stabiel': 'STABLE - stabiel',
  'veilig': 'FAIL-safe - SAFE',
  'gevaarlijk': 'Ge-FAR-lijk - DANGEROUS far',
  'gezond': 'Ge-SOUND - HEALTHY sound',
  'ziek': 'SICK - ziek',
  'sterk': 'STARK/STRONG - sterk',
  'zwak': 'WEAK - zwak',
  'fit': 'FIT - fit',
  'moe': 'MOE/TIRED - moe',
  'wakker': 'WACKER/AWAKE - wakker',
  'dood': 'DEAD - dood sounds like DEAD',
  'levend': 'LIVING - levend',
  'geboren': 'BORN - geboren',
  'getrouwd': 'Ge-TRUE-d - MARRIED truly',
  'gescheiden': 'Ge-SHED-en - DIVORCED/shed',
  'alleenstaand': 'ALONE-STAND - SINGLE standing alone',
  'zwanger': 'SWANGER - PREGNANT',
  'aanwezig': 'On-WES-ig - PRESENT/here',
  'afwezig': 'AF-WES-ig - ABSENT/away',
  'beschikbaar': 'Be-SCHICK-baar - AVAILABLE',
  'bezet': 'Be-SET - OCCUPIED/busy',
  'vrij': 'FREE - vrij sounds like FREE',
  'verplicht': 'For-PLIGHT - OBLIGATORY duty',
  'vrijwillig': 'FREE-WILL-ig - VOLUNTARY',
  'noodzakelijk': 'NOOD-ZAAK-elijk - NECESSARY need-sake',
  'onmogelijk': 'On-MOGE-lijk - IMPOSSIBLE',
  'waarschijnlijk': 'WHERE-SCHIJN-lijk - PROBABLY seems',
  'onwaarschijnlijk': 'Un-WHERE-SCHIJN-lijk - UNLIKELY',
  'zeker': 'SECURE/CERTAIN - zeker',
  'onzeker': 'Un-SECURE - UNCERTAIN',
  'duidelijk': 'DO-id-elijk - CLEAR/obvious',
  'onduidelijk': 'Un-DO-id-elijk - UNCLEAR',
  'eenvoudig': 'EEN-FOLD-ig - SIMPLE one-fold',
  'complex': 'COMPLEX - complex',
  'gemakkelijk': 'Ge-MAKE-elijk - EASY to make',
  'moeilijk': 'MOY-lijk - DIFFICULT',
  'zwaar': 'HEAVY - zwaar',
  'licht': 'LIGHT - licht',
  'vol': 'FULL - vol',
  'leeg': 'LEAGUE empty - EMPTY',
  'rijk': 'RICH - rijk',
  'arm': 'ARM/POOR - arm',
  'duur': 'DEAR/EXPENSIVE - duur',
  'goedkoop': 'GOOD-cheap - CHEAP',
  'gratis': 'GRATIS/FREE - gratis',
  'betaalbaar': 'Be-TAAL-baar - AFFORDABLE',
};

// Add mnemonics to words
let added = 0;
for (const word of words) {
  const mnemonic = moreMnemonics[word.dutch];
  if (mnemonic && !word.mnemonic) {
    word.mnemonic = mnemonic;
    added++;
  }
}

// Write back
fs.writeFileSync(wordsPath, JSON.stringify(words, null, 2));
console.log(`Added ${added} more mnemonics to words`);

// Count total
const total = words.filter(w => w.mnemonic).length;
console.log(`Total words with mnemonics: ${total}/${words.length}`);
